apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kotlin-reactive
  name: kotlin-reactive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kotlin-reactive
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-reactive
    spec:
      containers:
      - image: kotlin-reactive:latest
        name: kotlin-reactive
        imagePullPolicy: Never
        resources: {}
status: {}
