apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-reactive
  name: java-reactive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-reactive
  strategy: {}
  template:
    metadata:
      labels:
        app: java-reactive
    spec:
      containers:
      - image: java-reactive:0.0.1-SNAPSHOT
        name: java-reactive-44zzg
        imagePullPolicy: IfNotPresent
        resources: {}
        env:
          - name: PRINT_ME
            valueFrom:
              configMapKeyRef:
                name: java-reactive-config
                key: print_me
